package entidade;

// Generated 15/09/2013 23:36:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioFuncionamento generated by hbm2java
 */
@Entity
@Table(name = "tb_horario_funcionamento", catalog = "dbfastlunch")
public class HorarioFuncionamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idHorarioFuncionamento;
	private Date horarioAbertura;
	private Date horarioFechamento;
	private String diaSemana;
	private Boolean ativo;
	private Set<HorarioFuncionamentoDelivery> horarioFuncionamentoDeliveries = new HashSet<HorarioFuncionamentoDelivery>(
			0);
	private Set<HorarioFuncionamentoEstabelecimento> horarioFuncionamentoEstabelecimentos = new HashSet<HorarioFuncionamentoEstabelecimento>(
			0);

	public HorarioFuncionamento() {
	}

	public HorarioFuncionamento(Date horarioAbertura, Date horarioFechamento,
			String diaSemana) {
		this.horarioAbertura = horarioAbertura;
		this.horarioFechamento = horarioFechamento;
		this.diaSemana = diaSemana;
	}

	public HorarioFuncionamento(
			Date horarioAbertura,
			Date horarioFechamento,
			String diaSemana,
			Boolean ativo,
			Set<HorarioFuncionamentoDelivery> horarioFuncionamentoDeliveries,
			Set<HorarioFuncionamentoEstabelecimento> horarioFuncionamentoEstabelecimentos) {
		this.horarioAbertura = horarioAbertura;
		this.horarioFechamento = horarioFechamento;
		this.diaSemana = diaSemana;
		this.ativo = ativo;
		this.horarioFuncionamentoDeliveries = horarioFuncionamentoDeliveries;
		this.horarioFuncionamentoEstabelecimentos = horarioFuncionamentoEstabelecimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_horario_funcionamento", unique = true, nullable = false)
	public Long getIdHorarioFuncionamento() {
		return this.idHorarioFuncionamento;
	}

	public void setIdHorarioFuncionamento(Long idHorarioFuncionamento) {
		this.idHorarioFuncionamento = idHorarioFuncionamento;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario_abertura", nullable = false, length = 8)
	public Date getHorarioAbertura() {
		return this.horarioAbertura;
	}

	public void setHorarioAbertura(Date horarioAbertura) {
		this.horarioAbertura = horarioAbertura;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario_fechamento", nullable = false, length = 8)
	public Date getHorarioFechamento() {
		return this.horarioFechamento;
	}

	public void setHorarioFechamento(Date horarioFechamento) {
		this.horarioFechamento = horarioFechamento;
	}

	@Column(name = "dia_semana", nullable = false, length = 4)
	public String getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(String diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Column(name = "ativo")
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioFuncionamento")
	public Set<HorarioFuncionamentoDelivery> getHorarioFuncionamentoDeliveries() {
		return this.horarioFuncionamentoDeliveries;
	}

	public void setHorarioFuncionamentoDeliveries(
			Set<HorarioFuncionamentoDelivery> horarioFuncionamentoDeliveries) {
		this.horarioFuncionamentoDeliveries = horarioFuncionamentoDeliveries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioFuncionamento")
	public Set<HorarioFuncionamentoEstabelecimento> getHorarioFuncionamentoEstabelecimentos() {
		return this.horarioFuncionamentoEstabelecimentos;
	}

	public void setHorarioFuncionamentoEstabelecimentos(
			Set<HorarioFuncionamentoEstabelecimento> horarioFuncionamentoEstabelecimentos) {
		this.horarioFuncionamentoEstabelecimentos = horarioFuncionamentoEstabelecimentos;
	}

}
