package entidade;

// Generated 15/09/2013 23:36:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HorarioFuncionamentoDelivery generated by hbm2java
 */
@Entity
@Table(name = "tb_horario_funcionamento_delivery", catalog = "dbfastlunch")

@NamedQueries({
@NamedQuery(name="HorarioFuncionamentoDelivery.buscaHorariosPorEstabelecimento",
		query="SELECT hd"
			+ " FROM HorarioFuncionamentoDelivery hd"
			+ " WHERE hd.estabelecimento.idEstabelecimento = :idEstabelecimento"
			+ " AND hd.disponivel = true"
			+ " AND hd.horarioFuncionamento.ativo = true"),
			
@NamedQuery(name="HorarioFuncionamentoDelivery.buscaHorariosPorEstabelecimentoEDia",
			query="SELECT hd"
				+ " FROM HorarioFuncionamentoDelivery hd"
				+ " WHERE hd.estabelecimento.idEstabelecimento = :idEstabelecimento"
				+ " AND hd.disponivel = true"
				+ " AND hd.horarioFuncionamento.ativo = true"
				+ " AND hd.horarioFuncionamento.diaSemana = :diaSemana")		
})
public class HorarioFuncionamentoDelivery implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public static final String BUSCA_HORARIOS_DELIVERIES_POR_ESTABELECIMENTO = "HorarioFuncionamentoDelivery.buscaHorariosPorEstabelecimento";
	public static final String BUSCA_HORARIOS_DELIVERIES_POR_ESTABELECIMENTO_E_DIA = "HorarioFuncionamentoDelivery.buscaHorariosPorEstabelecimentoEDia";
	
	private Long idHorarioFuncionamentoDelivery;
	private HorarioFuncionamento horarioFuncionamento;
	private Estabelecimento estabelecimento;
	private Boolean disponivel;

	public HorarioFuncionamentoDelivery() {
	}

	public HorarioFuncionamentoDelivery(
			HorarioFuncionamento horarioFuncionamento, Delivery delivery) {
		this.horarioFuncionamento = horarioFuncionamento;
	}

	public HorarioFuncionamentoDelivery(
			HorarioFuncionamento horarioFuncionamento,
			Delivery delivery, Boolean disponivel,
			Estabelecimento estabelecimento) {
		this.horarioFuncionamento = horarioFuncionamento;
		this.disponivel = disponivel;
		this.estabelecimento = estabelecimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_horario_funcionamento_delivery", unique = true, nullable = false)
	public Long getIdHorarioFuncionamentoDelivery() {
		return this.idHorarioFuncionamentoDelivery;
	}

	public void setIdHorarioFuncionamentoDelivery(
			Long idHorarioFuncionamentoDelivery) {
		this.idHorarioFuncionamentoDelivery = idHorarioFuncionamentoDelivery;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade={CascadeType.PERSIST, CascadeType.MERGE})
	@JoinColumn(name = "id_horario_funcionamento", nullable = false)
	public HorarioFuncionamento getHorarioFuncionamento() {
		return this.horarioFuncionamento;
	}

	public void setHorarioFuncionamento(
			HorarioFuncionamento horarioFuncionamento) {
		this.horarioFuncionamento = horarioFuncionamento;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name = "id_estabelecimento", nullable = false)
	public Estabelecimento getEstabelecimento() {
		return estabelecimento;
	}

	public void setEstabelecimento(Estabelecimento estabelecimento) {
		this.estabelecimento = estabelecimento;
	}

	@Column(name = "disponivel")
	public Boolean getDisponivel() {
		return this.disponivel;
	}

	public void setDisponivel(Boolean disponivel) {
		this.disponivel = disponivel;
	}

}
