package entidade;

// Generated 15/09/2013 23:36:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "tb_produto", catalog = "dbfastlunch")
@NamedQuery(name="Produto.buscaPorNome",
			query="SELECT p " +
			"FROM Produto p WHERE p.nome = :nome")
public class Produto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public static final String BUSCA_PRODUTO_POR_NOME = "Produto.buscaPorNome";
	
	private Long idProduto;
	private String nome;
	private String descricao;
	private double preco;
	private String imagem;
	private boolean ativo;
	private double precoPromocional;
	private Integer pontuacaoFidelidade;
	private Boolean disponibilidadeFidelidade;
	private Set<FidelidadeTroca> fidelidadeTrocas = new HashSet<FidelidadeTroca>(
			0);
	private Set<CardapioProduto> tbCardapioProdutos = new HashSet<CardapioProduto>(
			0);

	public Produto() {
	}

	public Produto(String nome, String descricao, double preco, String imagem,
			boolean ativo) {
		this.nome = nome;
		this.descricao = descricao;
		this.preco = preco;
		this.imagem = imagem;
		this.ativo = ativo;
	}

	public Produto(String nome, String descricao, double preco, String imagem,
			boolean ativo, double precoPromocional, Integer pontuacaoFidelidade,
			Boolean disponibilidadeFidelidade,
			Set<FidelidadeTroca> fidelidadeTrocas,
			Set<CardapioProduto> tbCardapioProdutos) {
		this.nome = nome;
		this.descricao = descricao;
		this.preco = preco;
		this.imagem = imagem;
		this.ativo = ativo;
		this.precoPromocional = precoPromocional;
		this.pontuacaoFidelidade = pontuacaoFidelidade;
		this.disponibilidadeFidelidade = disponibilidadeFidelidade;
		this.fidelidadeTrocas = fidelidadeTrocas;
		this.tbCardapioProdutos = tbCardapioProdutos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_produto", unique = true, nullable = false)
	public Long getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(Long idProduto) {
		this.idProduto = idProduto;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao", nullable = false, length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "preco", nullable = false, precision = 10, scale = 0)
	public double getPreco() {
		return this.preco;
	}

	public void setPreco(double preco) {
		this.preco = preco;
	}

	@Column(name = "imagem", nullable = false, length = 250)
	public String getImagem() {
		return this.imagem;
	}

	public void setImagem(String imagem) {
		this.imagem = imagem;
	}

	@Column(name = "ativo", nullable = false)
	public boolean isAtivo() {
		return this.ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	@Column(name = "preco_promocional", precision = 10, scale = 0)
	public double getPrecoPromocional() {
		return this.precoPromocional;
	}

	public void setPrecoPromocional(double precoPromocional) {
		this.precoPromocional = precoPromocional;
	}

	@Column(name = "pontuacao_fidelidade")
	public Integer getPontuacaoFidelidade() {
		return this.pontuacaoFidelidade;
	}

	public void setPontuacaoFidelidade(Integer pontuacaoFidelidade) {
		this.pontuacaoFidelidade = pontuacaoFidelidade;
	}

	@Column(name = "disponibilidade_fidelidade")
	public Boolean getDisponibilidadeFidelidade() {
		return this.disponibilidadeFidelidade;
	}

	public void setDisponibilidadeFidelidade(Boolean disponibilidadeFidelidade) {
		this.disponibilidadeFidelidade = disponibilidadeFidelidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<FidelidadeTroca> getFidelidadeTrocas() {
		return this.fidelidadeTrocas;
	}

	public void setFidelidadeTrocas(Set<FidelidadeTroca> fidelidadeTrocas) {
		this.fidelidadeTrocas = fidelidadeTrocas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produto")
	public Set<CardapioProduto> getCardapioProdutos() {
		return this.tbCardapioProdutos;
	}

	public void setCardapioProdutos(Set<CardapioProduto> tbCardapioProdutos) {
		this.tbCardapioProdutos = tbCardapioProdutos;
	}

}
