package entidade;

// Generated 15/09/2013 23:36:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatusPedido generated by hbm2java
 */
@Entity
@Table(name = "tb_status_pedido", catalog = "dbfastlunch")
public class StatusPedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idStatusPedido;
	private Pedido pedido;
	private String statusPedido;
	private Date dataHora;

	public StatusPedido() {
	}

	public StatusPedido(Pedido pedido, String statusPedido, Date dataHora) {
		this.pedido = pedido;
		this.statusPedido = statusPedido;
		this.dataHora = dataHora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_status_pedido", unique = true, nullable = false)
	public Long getIdStatusPedido() {
		return this.idStatusPedido;
	}

	public void setIdStatusPedido(Long idStatusPedido) {
		this.idStatusPedido = idStatusPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Column(name = "status_pedido", nullable = false, length = 12)
	public String getStatusPedido() {
		return this.statusPedido;
	}

	public void setStatusPedido(String statusPedido) {
		this.statusPedido = statusPedido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora", nullable = false, length = 19)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

}
