package entidade;

// Generated 15/09/2013 23:36:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "tb_usuario", catalog = "dbfastlunch", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
@NamedQuery(name="Usuario.buscaPorLogin",
			query="SELECT u " +
			"FROM Usuario u WHERE u.login = :login")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public static final String BUSCA_USUARIO_POR_LOGIN = "Usuario.buscaPorLogin";
	
	private Long idUsuario;
	private String login;
	private String senha;
	private String tipoUsuario;
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Usuario() {
	}

	public Usuario(String login, String senha, String tipoUsuario,
			Set<Funcionario> funcionarios, Set<Cliente> clientes) {
		this.login = login;
		this.senha = senha;
		this.tipoUsuario = tipoUsuario;
		this.funcionarios = funcionarios;
		this.clientes = clientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_usuario", unique = true, nullable = false)
	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "login", unique = true, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "senha", length = 50)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "tipo_usuario", length = 5)
	public String getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "usuario", cascade=CascadeType.PERSIST)
	public Set<Funcionario> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "usuario")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
